export const questionsOjoSeco = [
    ["Padecimiento en el cual una persona no produce suficientes lágrimas de calidad para nutrir y lubricar al ojo","Enfermedad de Ojo Seco","Síndrome de Ojo Seco","Enfermedad de la película lagrimal","Daño en el Ojo Seco"],
    ["Cuáles son las 2 fases de la película lagrimal según la definición del DEWS II","Capa lipídica y mucino-acuosa","Capa lipídica y capa de mucina","Capara lipídica y capa acuosa","Capsula lipidia y capsula acuosa"],
    ["Menciona cuál de los siguientes es un síntoma de la enfermedad de Ojo Seco","A y C son correctas","Ojo rojo","Uso de antidepresivos","Sensación de arenilla"],
    ["Menciona cuál de los siguientes NO es un factor de riesgo para la enfermedad de Ojo Seco","Ardor","Edad","Condiciones médicas como diabetes","Enfermedades como diabetes"],
    ["Selecciona una función de la película lagrimal","Todas son correctas","Lleva oxígeno y nutrientes para la córnea","Mejora la visión","Humedece la superficie ocular"],
    ["Nombre de la estructura en las células normales que permiten que la fase mucino-acuosa permanezca protegiendo al ojo","Glicocálix","Epitelio","Descemet","Endotelio"],
    ["Número estimado de personas que padecen de Ojo Seco en el mundo","1400 Millones","140 Millones","14 Millones","140 Mil"],
    ["Menciona 2 de los principales factores de riesgo que pueden provocar Ojo Seco","Edad y Género","Edad","Cambio de clima","Género"],
    ["Molécula presente en todos los productos de la Familia Systane capaz de unirse a las zonas de la superficie ocular dañadas por el Ojo Seco, que permite que los pacientes experimenten un alivio rápido de larga duración","HP-Guar","HP-Guard","Polietilenglicol ","DropTainer"],
    ["Es uno de los cuestionarios que se pueden utilizar para saber si un paciente padece la enfermedad de Ojo Seco","DEQ5","OSDY","AOS","CDC"],
    ["Selecciona cuál de los siguientes enunciados es correcto","El ojo seco es un problema común y con frecuencia crónico, particularmente en adultos mayores","El ojo seco es un problema común y con frecuencia crónico, particularmente en niños","El ojo seco es un problema poco común y con frecuencia crónico, particularmente en adultos mayores","El ojo seco es un problema poco común y nunca crónico, particularmente en mujeres adultas"],
    ["Porcentaje de los pacientes con ojo seco que tienen signos clínicos de DGM","86%","56%","96%","78%"],
    ["Las Glándulas de Meibomio que forman la capa de lípidos de la Película Lagrimal, actúan como una barrera, retrasando la evaporación de la capa acuosa","La afirmación es cierta","La afirmación es falsa","Actúan como barrera, pero no retrasa la evaporación","Son otras glándulas las encargadas de estos procesos"],
    ["¿Cuál es el objetivo del manejo de la enfermedad de Ojo Seco?","A y C son correctas","Aliviar el malestar ocular","Quitar el enrojecimiento de los ojos","Lograr la homeostasis de la película lagrimal"],
    ["¿Cuál de los siguientes NO forma parte del diagnóstico de la enfermedad de Ojo Seco?","Cultivos","Preguntas de triaje","Análisis de factores de riesgo","Pruebas de clasificación de subtipos"],
    ["Forma parte de la primera línea de tratamiento de los pacientes con Enfermedad de Ojo Seco","Lubricantes oculares","Secretagogos orales","Tapones lagrimales","Abordaje quirúrgico"],
    ["En la tinción con fluoresceína el tiempo de rompimiento de la Película Lagrimal nos indica","Calidad de la película lagrimal","Cantidad de la película lagrimal","Severidad de los síntomas del paciente","Todas las anteriores"],
    ["Es el aspecto de la secreción que deben expresar las Glándulas de Meibomio","Transparente","Blanquecino","Amarillento","Gris claro"],
    ["Relación de pacientes que acuden a consulta que han comunicado tener al menos un síntoma de Ojo Seco","3 de cada 4 pacientes","2 de cada 4 pacientes","5 de cada 8","2 de cada 6"],
    ["Los pacientes con Enfermedad de Ojo Seco fueron 3 veces más propensos a informar dificultades para realizar las siguientes actividades","Todas son correctas","Leer","Trabajar en computadora","Manejar en la noche"],
    ["Porcentaje de la población en Latinoamérica que informó experimentar síntomas de Ojo Seco o Irritados según el MarketScope LLC 2019","30%","20%","90%","15%"],
    ["La DGM es una condición caracterizada por la insuficiencia de lípidos en la Película Lagrimal y además","Es la causa más común de Ojo Seco Evaporativo","Tiene su origen en la glándula lagrimal principal","Afecta solamente a las mujeres","Es la causa menos común de Ojo Seco Evaportativo"],
    ["¿El HP-Guar es un agente gelificante derivado de la planta Guar ¿Con qué está creado este componente?","Goma Guar Modificada","Hialuronato y Goma Guar","Borato","Sorbitol y goma Guar"],
    ["Cuál de las siguientes NO es una ventaja del HP-Guar","Reduce la lubricación","Mimetiza la capa de mucina","Protege y regenera la superficie ocular","Reduce la inflamación"],
    ["Grupo poblacional más afectado por la Enfermedad de Ojo Seco","Mujeres","Niños","Personas caucásicas","Hombres"],
    ["La exposición visual a las pantallas por más de cinco horas diarias ha provocado el aumento en pacientes que demandan consulta en el servicio de oftalmología con síntomas como","Todas son correctas","Visión borrosa","Dolor de ojos y cabeza asociados al esfuerzo ocular","Ojo seco"],
    ["Hormonas principales u hormona principal, cuyos niveles fluctuantes pueden afectar las glándulas sebáceas de los ojos, llevando al resecamiento","Estrógeno y Progesterona","Progesterona","Estrogeno","Lutropina"],
    ["Pruebas de detección necesarias en el diagnóstico de la enfermedad de Ojo Seco","Todas son correctas","Medir el volumen de las lágrimas (Prueba de Schirmer o Prueba del Hilo de Fenol)","Determinarse la calidad de las lágrimas midiendo la composición de partículas y agua","Utilización de marcadores para detectar la enfermedad en las lágrimas recolectadas"],
    ["Condición caracterizada por la alteración en el contenido (cantidad y/o calidad) y o pobre distribución lipídica en la película lagrimal que provoca la evaporación de la lágrima","DGM","Sjögren","DMAE","MGDSa"]
]

export const questionsLubricantes = [
    ["Producto de la familia Systane ideal como primera opción para tratar a los nuevos pacientes con Síntomas de Ojo Seco","Systane Complete","Systane Gel","Systane HA","Systane Utra"],
    ["Producto ideal para tratar los pacientes con Ojo Seco Ocasional","Systane Utra","Systane Gel","Systane HA","Systane Complete"],
    ["Es la combinación de HA + HP-Guar que ayuda con la humectación y la reepitelización de la superficie ocular en un solo producto","Systane HA","Systane Gel","Systane Complete","Systane Utra"],
    ["Puede indicar el uso de este producto en sus pacientes que necesiten protección adicional en el tratamiento de la Enfermedad de Ojo Seco","Systane Gel","Systane HA","Systane Complete","Systane Utra"],
    ["Las siguientes son características del HP Guar","Todas las opciones","Se une a la glicocálix","Es una molécula muy estable","Aumenta la estabilidad de la película lagrimal "],
    ["Matríz protectora que proporciona un mayor tiempo de retención de la lagrima en la superficie ocular, así como una protección prolongada","HP Guar + Borato","HA + PEG","Borato + Sorbitol","HP Guar + Sorbitol"],
    ["Integrante de la familia systane recomendado en el manejo de la enfermedad de ojo seco por deficiencia musino acuosa","Systane HA y Systane Ultra","Solo Systane Balance","Solo Systane HA","Solo Systane Ultra"],
    ["Es el nombre del gotero patentado por Alcon, que ayuda a instilar sólo una gota en caso de la Familia Systane","Droptainer","HP GUAR","Drop GUAR","Drop Line"],
    ["Horas de alivio sostenido que provee la formulación de Systane Complete","8 hrs de alivio","4 hrs de alivio","12 hrs de alivio","6 hrs de alivio"],
    ["Son ingredientes activos en el frasco de la formulación de Systane HA","Hialuronato de sodio, polietilenglicol y propilenglicol","Hialuronato de sodio, HP Guar y Borato","HP Guar y borato","Ninguna de las anterioreS"],
    ["¿Cuáles son las ventajas del HP-uar en Systane?","Todas las respuestas son correctas","Mimetiza la capa de mucina","Protege y regenera la superficie ocular","Reduce la inflamación"],
    ["Selecciona qué ventajas tiene el alivio prolongado de 8 horas de Systane Complete en el tratamiento de los pacientes con Ojo Seco","Todas las opciones son correctas","Permite que el tratamiento dure más tiempo","Actúa sobre todas las capas de la película lagrimal","Son menos instilaciones"],
    ["Producto de la familia Systane que mejora la cicatrización corneal, ideal para el uso en pacientes en el post operatorio","Systane HA","Systane Gel","Systane Complete","Systane Ultra"],
    ["Es conocido como un “Imán de humedad” natural que ayuda a los lubricantes a proporcionar hidratación más duradera, permaneciendo más tiempo en la superficie ocular gracias al HP-Guar","HA","Carboximetilcelulosa","Glicerina","Sorbitol"]
]